
export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";

export const FETCH_CLIENT_LIST_REQUEST = "FETCH_CLIENT_LIST_REQUEST";
export const FETCH_CLIENT_LIST_SUCCESS = "FETCH_CLIENT_LIST_SUCCESS";
export const FETCH_CLIENT_LIST_FAILURE = "FETCH_CLIENT_LIST_FAILURE";

export const SAVE_CLIENT_REQUEST = "SAVE_CLIENT_REQUEST";
export const SAVE_CLIENT_SUCCESS = "SAVE_CLIENT_SUCCESS";
export const SAVE_CLIENT_FAILURE = "SAVE_CLIENT_FAILURE";

export const SAVE_ACTIVITY_REQUEST = "SAVE_ACTIVITY_REQUEST";
export const SAVE_ACTIVITY_SUCCESS = "SAVE_ACTIVITY_SUCCESS";
export const SAVE_ACTIVITY_FAILURE = "SAVE_ACTIVITY_FAILURE";



export const SET_MAIN_PAGE = "SET_MAIN_PAGE";
export const SET_SELECTED_CLIENT = "SET_SELECTED_CLIENT";


export const UI_LOGIN_PAGE = "UI_LOGIN_PAGE";
export const UI_CLIENT_LIST = "UI_CLIENT_LIST";
export const UI_CLIENT_DETAILS = "UI_CLIENT_DETAILS";
export const UI_ADD_CLIENT_FORM = "UI_ADD_CLIENT_FORM";


export const ALERT_TYPE_INFO = "ALERT_TYPE_INFO";
export const ALERT_TYPE_SUCCESS = "ALERT_TYPE_SUCCESS";
export const ALERT_TYPE_WARNNG = "ALERT_TYPE_WARNNG";
export const ALERT_TYPE_ERROR = "ALERT_TYPE_ERROR";